/**
 * modsAdapter — typed access to the build-time mods-map.json.
 *
 * mods-map.json is generated by `scripts/generate-mods-map.mjs` from the
 * @wfcd/items package. It contains per-rank levelStats so the Scholar's
 * Arcanum mod page can render the variant rank grid fully offline.
 *
 * Import pattern: the JSON is bundled by Vite at build time. For the
 * Tauri desktop target (~1MB is a one-time load from disk), this is fine.
 */

import modsRaw from './mods-map.json';

// ─── Types ────────────────────────────────────────────────────────────────────

export type ModRarity = 'Common' | 'Uncommon' | 'Rare' | 'Legendary';

export type ModPolarity =
  | 'madurai'
  | 'vazarin'
  | 'naramon'
  | 'zenurik'
  | 'unairu'
  | 'penjaga'
  | 'umbra'
  | 'aura'
  | 'universal'
  | 'none';

export interface ModEntry {
  uniqueName:  string;
  name:        string;
  imageName:   string | null;
  rarity:      ModRarity;
  drain:       number;
  polarity:    ModPolarity | null;
  type:        string;
  description: string;
  /** Per-rank stat lines. levelStats[0] = R0 stats, levelStats[N] = RN stats. */
  levelStats:  string[][];
  /** Short weapon/compat label shown at bottom of card (SHOTGUN, RIFLE, etc.) */
  compatName:  string;
  tradeable:   boolean;
  /** Resolved CDN icon URL — set after calling resolveModIconUrl(). */
  iconUrl?:    string;
}

// ─── Raw map import ───────────────────────────────────────────────────────────

type RawModMap = Record<string, Omit<ModEntry, 'uniqueName' | 'iconUrl'>>;
const rawMap = modsRaw as RawModMap;

// ─── Derived lookup structures (built once, module-level) ─────────────────────

let _all: ModEntry[] | null = null;
let _byUniqueName: Map<string, ModEntry> | null = null;
let _byName: Map<string, ModEntry> | null = null;

function ensureBuilt(): void {
  if (_all) return;

  _all = [];
  _byUniqueName = new Map();
  _byName = new Map();

  for (const [uniqueName, raw] of Object.entries(rawMap)) {
    const entry: ModEntry = { ...raw, uniqueName, rarity: raw.rarity as ModRarity };
    _all.push(entry);
    _byUniqueName.set(uniqueName, entry);
    _byName.set(raw.name.toLowerCase(), entry);
  }

  // Sort alphabetically for the browse list
  _all.sort((a, b) => a.name.localeCompare(b.name));
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** All mods, sorted alphabetically. */
export function getAllMods(): ModEntry[] {
  ensureBuilt();
  return _all!;
}

/** Look up a mod by its WFCD uniqueName. */
export function getModByUniqueName(uniqueName: string): ModEntry | undefined {
  ensureBuilt();
  return _byUniqueName!.get(uniqueName);
}

/** Look up a mod by its display name (case-insensitive). */
export function getModByName(name: string): ModEntry | undefined {
  ensureBuilt();
  return _byName!.get(name.toLowerCase());
}

/**
 * Filter mods for the browse list. All params are optional.
 * Returns a filtered + sorted (alphabetical) slice.
 */
export function searchMods(opts: {
  query?:    string;
  rarity?:   ModRarity | 'all';
  compatName?: string;
}): ModEntry[] {
  ensureBuilt();
  const { query = '', rarity = 'all', compatName } = opts;
  const q = query.toLowerCase().trim();

  return _all!.filter((m) => {
    if (q && !m.name.toLowerCase().includes(q)) return false;
    if (rarity !== 'all' && m.rarity !== rarity) return false;
    if (compatName && m.compatName !== compatName) return false;
    // Skip mods with no levelStats (data gaps / internal stubs)
    if (m.levelStats.length === 0) return false;
    return true;
  });
}

/** All unique compat names present in the mod list (sorted). */
export function getAllCompatNames(): string[] {
  ensureBuilt();
  const names = new Set(_all!.map((m) => m.compatName));
  return [...names].sort();
}

/** Number of ranks (0-indexed). e.g. 11 levelStats entries → R0–R10. */
export function modRankCount(mod: ModEntry): number {
  return mod.levelStats.length;
}

/** Max rank index (e.g. 10 for an 11-rank mod). */
export function modMaxRank(mod: ModEntry): number {
  return Math.max(0, mod.levelStats.length - 1);
}
